name: 'XML file validation'

on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  validate_xml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Linting
        uses: ChristophWurst/xmllint-action@v1
        with:
          xml-file: ./*/*.xml