name: 'XML file validation'

on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  validate_xml:
  runs-on: macos-latest
  steps:
    - name: Validate
      run: 'xmllint --noout ./*.xml'