name: 'XML file validation'

on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  validate_xml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install xmllint
        run: sudo apt-get install --no-install-recommends -y libxml2-utils
      - uses: korelstar/xmllint-problem-matcher@v1

      - name: Validate
        run: xmllint --noout ./*/*.xml