name: 'XML file validation'

on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read
  pull_requests: read

jobs:
  validate_xml:
    steps:
      - name: Validate
        run: 'xmllint --noout ./*.xml'